version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root    
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=gadgethub_db
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/gadgethub_db?sslmode=disable
    depends_on:
      - postgres