CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR NOT NULL,
  "email" VARCHAR UNIQUE NOT NULL,
  "hash_password" VARCHAR NOT NULL,
  "phone" VARCHAR NOT NULL,
  "is_admin" BOOLEAN NOT NULL
);

CREATE TABLE "discount_coupons" (
  "coupon_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_by" INT NOT NULL,
  "created_at" DATE NOT NULL,
  "valid_until" DATE NOT NULL
);

CREATE TABLE "categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR NOT NULL
);

CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" VARCHAR NOT NULL,
  "price" DECIMAL NOT NULL,
  "stock" INT NOT NULL,
  "category_id" INT NOT NULL,
  "brand" VARCHAR,
  "model" VARCHAR
);

CREATE TABLE "orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL,
  "order_date" DATE NOT NULL,
  "status" VARCHAR NOT NULL,
  "total_amount" DECIMAL NOT NULL
);

CREATE TABLE "order_items" (
  "order_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" INT NOT NULL,
  "product_id" INT NOT NULL,
  "coupon_id" INT,
  "quantity" INT NOT NULL,
  "unit_price" DECIMAL NOT NULL
);

CREATE TABLE "reviews" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  "rating" INT NOT NULL,
  "review_date" DATE NOT NULL
);

CREATE TABLE "cart_items" (
  "cart_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL,
  "product_id" INT NOT NULL,
  "quantity" INT NOT NULL
);

CREATE INDEX ON "products" ("category_id");

CREATE INDEX ON "orders" ("user_id");

CREATE INDEX ON "order_items" ("order_id");

CREATE INDEX ON "order_items" ("product_id");

CREATE INDEX ON "reviews" ("product_id");

CREATE INDEX ON "reviews" ("user_id");

CREATE INDEX ON "cart_items" ("user_id");

CREATE INDEX ON "cart_items" ("product_id");

ALTER TABLE "discount_coupons" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("user_id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("coupon_id") REFERENCES "discount_coupons" ("coupon_id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");
