CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "hash_password" varchar NOT NULL,
  "phone" varchar NOT NULL,
  "isAdmin" bool NOT NULL
);

CREATE TABLE "discount_coupons" (
  "coupon_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_by" int NOT NULL,
  "created_at" date NOT NULL,
  "valid_until" date NOT NULL
);

CREATE TABLE "categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL
);

CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "price" decimal NOT NULL,
  "stock" int NOT NULL,
  "category_id" int NOT NULL,
  "brand" varchar,
  "model" varchar
);

CREATE TABLE "orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "from_cart_id" int NOT NULL,
  "order_date" date NOT NULL,
  "status" varchar NOT NULL,
  "total_amount" decimal NOT NULL
);

CREATE TABLE "order_Items" (
  "order_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "product_id" int NOT NULL,
  "coupon_id" int,
  "quantity" int NOT NULL,
  "unit_price" decimal NOT NULL
);

CREATE TABLE "reviews" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "user_id" int NOT NULL,
  "rating" int NOT NULL,
  "review_date" date NOT NULL
);

CREATE TABLE "cart_Items" (
  "cart_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int NOT NULL
);

CREATE INDEX ON "products" ("category_id");

CREATE INDEX ON "orders" ("user_id");

CREATE INDEX ON "order_Items" ("order_id");

CREATE INDEX ON "order_Items" ("product_id");

CREATE INDEX ON "reviews" ("product_id");

CREATE INDEX ON "reviews" ("user_id");

CREATE INDEX ON "cart_Items" ("user_id");

CREATE INDEX ON "cart_Items" ("product_id");

ALTER TABLE "discount_coupons" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("user_id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("from_cart_id") REFERENCES "cart_Items" ("cart_item_id");

ALTER TABLE "order_Items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "order_Items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "order_Items" ADD FOREIGN KEY ("coupon_id") REFERENCES "discount_coupons" ("coupon_id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "cart_Items" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "cart_Items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");
