CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fist_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "hash_password" varchar NOT NULL,
  "phone" varchar NOT NULL,
  "is_admin" bool NOT NULL
);

CREATE TABLE "discount_coupons" (
  "coupon_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_by" int NOT NULL,
  "created_at" date NOT NULL,
  "valid_until" date NOT NULL
);

CREATE TABLE "categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL
);

CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "price" decimal NOT NULL,
  "stock" int NOT NULL,
  "category_id" int NOT NULL,
  "brand" varchar,
  "model" varchar
);

CREATE TABLE "orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "order_date" date NOT NULL,
  "status" varchar NOT NULL,
  "total_amount" decimal NOT NULL
);

CREATE TABLE "order_items" (
  "order_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "product_id" int NOT NULL,
  "coupon_id" int,
  "quantity" int NOT NULL,
  "unit_price" decimal NOT NULL
);

CREATE TABLE "Reviews" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "user_id" int NOT NULL,
  "rating" int NOT NULL,
  "review_date" date NOT NULL
);

CREATE TABLE "cart_items" (
  "cart_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int NOT NULL
);

CREATE INDEX ON "Products" ("category_id");

CREATE INDEX ON "Orders" ("user_id");

CREATE INDEX ON "Order_Items" ("order_id");

CREATE INDEX ON "Order_Items" ("product_id");

CREATE INDEX ON "Reviews" ("product_id");

CREATE INDEX ON "Reviews" ("user_id");

CREATE INDEX ON "Cart_Items" ("user_id");

CREATE INDEX ON "Cart_Items" ("product_id");

ALTER TABLE "DiscountCoupons" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("user_id");

ALTER TABLE "Products" ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("category_id");

ALTER TABLE "Orders" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Order_Items" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id");

ALTER TABLE "Order_Items" ADD FOREIGN KEY ("product_id") REFERENCES "Products" ("product_id");

ALTER TABLE "Order_Items" ADD FOREIGN KEY ("coupon_id") REFERENCES "DiscountCoupons" ("coupon_id");

ALTER TABLE "Reviews" ADD FOREIGN KEY ("product_id") REFERENCES "Products" ("product_id");

ALTER TABLE "Reviews" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Cart_Items" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Cart_Items" ADD FOREIGN KEY ("product_id") REFERENCES "Products" ("product_id");
