// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  fist_name,
  last_name,
  email,
  phone,
  is_admin
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING user_id, fist_name, last_name, email, password, phone, is_admin
`

type CreateUserParams struct {
	FistName string `json:"fist_name"`
	LastName string `json:"last_name"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	IsAdmin  bool   `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FistName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FistName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.IsAdmin,
	)
	return i, err
}
