-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2024-05-08T05:58:11.571Z

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "hash_password" varchar NOT NULL,
  "phone" varchar UNIQUE NOT NULL,
  "user_role" varchar NOT NULL
);

CREATE TABLE "discount_coupons" (
  "coupon_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_by" int NOT NULL,
  "created_at" date NOT NULL,
  "expires_at" date NOT NULL
);

CREATE TABLE "categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL
);

CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "price" decimal NOT NULL,
  "stock" int NOT NULL,
  "category_id" int NOT NULL,
  "brand" varchar,
  "model" varchar
);

CREATE TABLE "orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "user_id" int NOT NULL,
  "coupon_id" int,
  "price" decimal NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "reviews" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "rating" int NOT NULL,
  "review_date" date NOT NULL
);

CREATE TABLE "chat_messages" (
  "chat_message_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_session_id" int NOT NULL,
  "message_received" varchar,
  "message_sent" varchar,
  "received_at" timestamptz,
  "sent_at" timestamptz,
  "action" varchar NOT NULL,
  "message_before_id" int
);

CREATE TABLE "chat_sessions" (
  "chat_session_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "last_message_id" int,
  "action_flow" varchar NOT NULL,
  "user_id" int NOT NULL,
  "payload" varchar NOT NULL,
  "opened_at" timestamptz NOT NULL DEFAULT (now()),
  "closed_at" timestamptz
);

CREATE INDEX ON "products" ("category_id");

CREATE INDEX ON "orders" ("order_id");

CREATE INDEX ON "orders" ("product_id");

CREATE INDEX ON "reviews" ("order_id");

CREATE INDEX ON "chat_messages" ("chat_session_id");

CREATE INDEX ON "chat_sessions" ("user_id");

ALTER TABLE "discount_coupons" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("user_id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("coupon_id") REFERENCES "discount_coupons" ("coupon_id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("chat_session_id") REFERENCES "chat_sessions" ("chat_session_id");

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("message_before_id") REFERENCES "chat_messages" ("chat_message_id");

ALTER TABLE "chat_sessions" ADD FOREIGN KEY ("last_message_id") REFERENCES "chat_messages" ("chat_message_id");

ALTER TABLE "chat_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
