apiVersion: apps/v1
kind: Deployment
metadata:
  name: gadgethub-api-deployment
  labels:
    app: gadgethub-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gadgethub-api
  template:
    metadata:
      labels:
        app: gadgethub-api
    spec:
      containers:
      - name: gadgethub-api
        image: 708343447892.dkr.ecr.eu-central-1.amazonaws.com/gadgethub:892289c4e1dc08ac223a347e9f8a420b4eacb7d9
        ports:
        - containerPort: 8080
